// Generated by tools/generate_assets.py. Edit config/metrics.json.
module Metrics {
    const NONE = 0;
    const STEPS = 1;
    const BODY = 2;
    const ALTITUDE = 3;
    const PRESSURE = 4;
    const CALORIES = 5;
    const BATTERY = 6;
    const HEART = 7;
    const DISTANCE = 8;
    const STRESS = 9;
    const OXYGEN = 10;
    const TEMPERATURE = 11;
    const HUMIDITY = 12;
    const RAIN = 13;
    const WIND = 14;
    const NOTIFICATIONS = 15;
    const ACTIVE = 16;
    const SUNRISE = 17;
    const SUNSET = 18;
    const COUNT = 19;
    const ICONS = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""];
    const UNITS = ["", "", "", "m", "", "", "%", "", "k", "", "%", "°", "%", "%", "", "", "", "", ""];
}
